// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnFo8JHFhnRBJgl0ZpwVaTRJEC5YRMq-8',
    appId: '1:872576359650:web:4ce3c7e53ae16f310152bb',
    messagingSenderId: '872576359650',
    projectId: 'dbs-cool-fim-project',
    authDomain: 'dbs-cool-fim-project.firebaseapp.com',
    storageBucket: 'dbs-cool-fim-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLE7j0CVj1EchowtNB36aWbAdu4hrWf9U',
    appId: '1:872576359650:android:9ce1ff5374fd43b40152bb',
    messagingSenderId: '872576359650',
    projectId: 'dbs-cool-fim-project',
    storageBucket: 'dbs-cool-fim-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLO1WH0OE2EJr1g8YoQ1rRKTlCDos55rg',
    appId: '1:872576359650:ios:355990729fcd78420152bb',
    messagingSenderId: '872576359650',
    projectId: 'dbs-cool-fim-project',
    storageBucket: 'dbs-cool-fim-project.appspot.com',
    iosClientId: '872576359650-8eeahc7rb8o6qs5qd4j24b4g9p265v2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbs2FrontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLO1WH0OE2EJr1g8YoQ1rRKTlCDos55rg',
    appId: '1:872576359650:ios:355990729fcd78420152bb',
    messagingSenderId: '872576359650',
    projectId: 'dbs-cool-fim-project',
    storageBucket: 'dbs-cool-fim-project.appspot.com',
    iosClientId: '872576359650-8eeahc7rb8o6qs5qd4j24b4g9p265v2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbs2FrontEnd',
  );
}
